version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: 'redis'
    ports:
      - '6379:6379'
    networks:
      mobile-monitoring:
  postgres-db:
    image: postgres:15.3-alpine3.18
    container_name: 'postgres-db'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mobile-monitoring:
    
volumes: 
  postgres-data: