namespace BlueXT.MobileMonitoring.EntityFrameworkCore;

public abstract class MobileMonitoringEntityFrameworkCoreTestBase : MobileMonitoringTestBase<MobileMonitoringEntityFrameworkCoreTestModule>
{
}
